StudentRegistration_SunionS/login/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^analytic/', TemplateView.as_view(template_name='analytic.html'), name ='analy'),
    url(r'^student/', include('student.urls'), name = 'student'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StudentRegistration_SunionS/student/urls.py
from django.conf.urls import url
from . import views

app_name = 'student'

urlpatterns = [

    url(r'^$',views.IndexView.as_view(), name ='index'),

    url(r'^researchc$',views.ResearchCount, name ='research-count'),

    url(r'^totalclec/$', views.totalCostLec, name='totalc-lec'),

    url(r'^totalcdep/$', views.totalCostDep, name='totalc-dep'),

    url(r'^avgdep/$', views.AVGdepartment, name='avg-dep'),

    url(r'^students/$', views.StudentIndex, name='Sindex'),

    url(r'^studentform/$', views.StudentFormView, name='studentform'),

    url(r'^studentmanage/$', views.StudentManageView.as_view(), name='student-manage'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail' ),

    url(r'student/add/$', views.StudentCreate.as_view(), name='student-add'),

    url(r'student/(?P<pk>[0-9]+)/$', views.StudentUpdate.as_view(), name='student-update'),

    url(r'student/(?P<pk>[0-9]+)/delete/$', views.StudentDelete.as_view(), name='student-delete'),

    url(r'department/add/$',views.DepartmentCreate.as_view(), name='department-add'),

    url(r'department/(?P<pk>[0-9]+)/$', views.DepartmentUpdate.as_view(), name='department-update'),

    url(r'department/(?P<pk>[0-9]+)/delete/$', views.DepartmentDelete.as_view(), name='department-delete'),

    url(r'^lindex/$', views.LIndexView.as_view(), name='Lindex'),

    url(r'^lindex/(?P<pk>[0-9]+)/$',views.LDetailView.as_view(), name='Ldetail'),

    url(r'lecturer/lindex/add/$',views.LecturerCreate.as_view(), name='lecturer-add'),

    url(r'research/lindex/add/$', views.ResearchCreate.as_view(), name='research-add'),

    url(r'lecturer/lindex/(?P<pk>[0-9]+)/$', views.LecturerUpdate.as_view(), name='lecturer-update'),

    url(r'research/lindex/(?P<pk>[0-9]+)/$', views.ResearchUpdate.as_view(), name='research-update'),

    url(r'research/lindex/(?P<pk>[0-9]+)/delete/$', views.ResearchDelete.as_view(), name='research-delete'),

    url(r'lecturer/lindex/(?P<pk>[0-9]+)/delete/$', views.LecturerDelete.as_view(), name='lecturer-delete'),

    url(r'course/lindex/add/$', views.CourseCreate.as_view(), name='course-add'),

    url(r'course/lindex/assign/$', views.AssignLecturer.as_view(), name='course-assign'),

    url(r'^course/$', views.CIndexView.as_view(), name='Cindex'),

    url(r'^course/lindex/(?P<pk>[0-9]+)/$', views.CDetailView.as_view(), name='Cdetail'),

    url(r'history/lindex/upgrade/(?P<pk>[0-9]+)/$', views.HistoryUpdate.as_view(), name='history-grade'),

    url(r'history/lindex/delete/(?P<pk>[0-9]+)/$', views.HistoryDelete.as_view(), name='history-delete'),

    url(r'course/lindex/upgrade/(?P<pk>[0-9]+)/$', views.CourseUpdate.as_view(), name='course-update'),

    url(r'course/lindex/delete/(?P<pk>[0-9]+)/$', views.CourseDelete.as_view(), name='course-delete'),

    url(r'^studentmanage/history/$', views.StudentHistory.as_view(), name='student-history'),

    url(r'^studentmanage/history/(?P<pk>[0-9]+)/$', views.HistoryDetail.as_view(), name='history-detail'),

    url(r'^studentmanage/test/add/$', views.AddSubject.as_view(), name='add-subject'),

    url(r'^studentmanage/test/add/(?P<pk>[0-9]+)/$', views.SubjectUpdate.as_view(), name='subject-update'),

    url(r'^students/profile/$', views.SDetailView.as_view(), name='Sdetail'),

    url(r'^studentmanage/test/$', views.Test.as_view(), name='Test'),

    url(r'^studentmanage/test/(?P<pk>[0-9]+)/$', views.RegisterUpdate.as_view(), name='register-update'),



]

StudentRegistration_SunionS/student/models.py
from django.db import models
from django.urls import reverse
import datetime

# Create your models here.

class Department(models.Model):
    DepNo = models.CharField(max_length = 4, default='xxxx')
    DepName = models.CharField(max_length = 30)
    DepTel = models.CharField(max_length=12)
    DepEmail = models.CharField(max_length = 50)
    DepHead = models.CharField(max_length = 11)
    Dep_logo = models.ImageField()

    def get_absolute_url(self):
        return reverse('student:detail', kwargs = {'pk': self.pk})

    def __str__(self):
        return self.DepNo + '--' + self.DepName

class Curriculum(models.Model):
    cur_dep_FK = models.ForeignKey(Department, on_delete = models.CASCADE)
    cCurriculum = models.CharField(max_length = 30)

    def __str__(self):
        return self.cur_dep_FK.DepName + '--' + self.cCurriculum

class Credit(models.Model):
    cre_cur_FK = models.ForeignKey(Curriculum, on_delete = models.CASCADE)
    thYear = models.CharField(max_length = 1, default = '-')
    CreditRequire = models.IntegerField()
    Semester = models.CharField(max_length = 20, default='X/YYYY')

    def __str__(self):
        return self.cre_cur_FK.cCurriculum + '--' + 'yr' + self.thYear + '--' + self.Semester

class Lecturer(models.Model):
    lec_dep_FK = models.ForeignKey(Department, on_delete = models.CASCADE, default='DEP')
    LecturerID = models.CharField(max_length = 11)
    LecturerDegree = models.CharField(max_length=20)
    LecturerName = models.CharField(max_length = 50)
    LecturerAddress = models.CharField(max_length = 100, default=None, blank=True, null=True)
    LecturerTel = models.CharField(max_length = 12, default=None, blank=True, null=True)
    LecturerRating = models.FloatField(default=None, blank=True, null=True)
    LecturerEmail = models.CharField(max_length = 50, default=None, blank=True, null=True)
    LecturerProfile = models.ImageField()

    def get_absolute_url(self):
        return reverse('student:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.LecturerName

class LecturerResearch(models.Model):
    research_lec_FK = models.ForeignKey(Lecturer,on_delete=models.CASCADE)
    ResearchName = models.CharField(max_length=30)
    Category =	models.CharField(max_length=20)
    Description = models.CharField(max_length=150)


    def get_absolute_url(self):
        return reverse('student:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.ResearchName + ' -- ' + self.Category

class Student(models.Model):
    stu_dep_FK = models.ForeignKey(Department, on_delete = models.CASCADE, default='DEP')
    StudentID = models.CharField(max_length=11)
    Degree = models.CharField(max_length = 20, default='DEG')
    name = models.CharField(max_length = 50, default='NAME')
    DOB = models.DateField()
    Tel = models.CharField(max_length = 12, default='TEL', blank=True, null=True)
    Email = models.CharField(max_length = 12, default=None, blank=True, null=True)
    GPAX = models.FloatField(null=True)
    Address = models.CharField(max_length = 100, default=None, blank=True, null=True)
    Status = models.CharField(max_length = 20, default='Normal')
    CurrentSemester = models.CharField(max_length = 20, default='X/YYYY')
    Curriculum = models.CharField(max_length = 20, default='CURRICULUM NAME')
    StudentProfile = models.ImageField()

    def __str__(self):
        return self.name

class Register(models.Model):
    RegNo = models.CharField(max_length=15)
    Date = models.DateField()
    reg_stu_FK = models.ForeignKey(Student, on_delete = models.CASCADE)
    Cost = models.FloatField()
    Discount = models.FloatField()
    PaymentMethod = models.CharField(max_length = 10)
    PaymentStatus = models.CharField(max_length = 10)
    PaymentDate = models.DateField(default=None, blank=True, null=True)
    Semester = models.CharField(max_length = 20, default='X/YYYY')

    def __str__(self):
        return self.RegNo


class Advisor(models.Model):
    adv_stu_FK = models.ForeignKey(Student, on_delete = models.CASCADE)
    adv_lec_FK = models.ForeignKey(Lecturer, on_delete = models.CASCADE)
    order = models.IntegerField()
    def __str__(self):
        return self.adv_stu_FK.name + '--'+ self.adv_lec_FK.LecturerName + '--' + str(self.order)

class Subject(models.Model):
    sub_sec_FK = models.ForeignKey('Section', on_delete=models.CASCADE, blank=True, null=True)
    SubjectID = models.CharField(max_length=8)
    SubjectName = models.CharField(max_length=30)
    Prerequisite = models.CharField(max_length=8, default=None, blank=True, null=True)
    Semester = models.CharField(max_length = 20, default='X/YYYY')
    Credit = models.IntegerField(default=3)

    def __str__(self):
        return self.SubjectName

class Section(models.Model):
    sec_subject_FK = models.ForeignKey(Subject, on_delete=models.CASCADE,default=None, blank=True, null=True)
    SectionNo = models.CharField(max_length=2)
    TotalSeat = models.IntegerField()
    LessonTime = models.CharField(max_length=20)

    def __str__(self):
        return '%s' % (self.SectionNo)

class LecturerInSection(models.Model):
    lecsec_sub_FK = models.ForeignKey(Subject, on_delete = models.CASCADE)
    lecsec_sec_FK = models.ForeignKey(Section, on_delete = models.CASCADE)
    lecsec_lec_FK = models.ForeignKey(Lecturer, on_delete = models.CASCADE)
    order = models.IntegerField()

    def __str__(self):
        return self.lecsec_lec_FK.LecturerName + '--' + self.lecsec_sub_FK.SubjectName + '--' + self.lecsec_sec_FK.SectionNo + '--' + str(self.order)

class History(models.Model):
    his_student_FK = models.ForeignKey(Student, on_delete=models.CASCADE)
    his_subject_FK = models.ForeignKey(Subject, on_delete=models.CASCADE)
    StudyYet = models.BooleanField()
    Grade = models.CharField(max_length=2)

    def __str__(self):
        return self.his_student_FK.name + '--' + self.his_subject_FK.SubjectName

StudentRegistration_SunionS/student/templates/student/Ldetail.html
{% extends 'student/Lbase.html' %}
{% block tittle %}{{ lecturer }}{% endblock %}
{% block lecturers_active %}active{% endblock %}

{% block body %}
<div class="container-fluid research-container">

    <div class="row">

       <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'student:Ldetail' lecturer.id %}">
                        {% if lecturer.LecturerProfile %}
                            <img src="{{ lecturer.LecturerProfile.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{lecturer.LecturerDegree}} {{ lecturer.LecturerName }}</h1>
                    <h3>DepNo:{{lecturer.lec_dep_FK}}</h3>
                    <h3>ID:{{lecturer.LecturerID}}</h3>
                    <h3>Address:{{lecturer.LecturerAddress}}</h3>
                    <h3>Tel:{{lecturer.LecturerTel}}</h3>
                    <h3>Email:{{lecturer.LecturerEmail}}</h3>

                </div>
            </div>
        </div>





        <!-- Right Song Info -->

        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h1>All research</h1>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                           <th>ResearchName</th>
                            <th>LecturerID</th>
                            <th>Category</th>
                            <th>Description</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for research in lecturer.lecturerresearch_set.all %}
                            <tr>
                                <td>{{research.ResearchName}}</td>
                                <td>{{research.research_lec_FK}}</td>
                                <td>{{research.Category}}</td>
                                <td>{{research.Description}}</td>
                                <td>
                                    <form action="{% url 'student:research-delete' research.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="research_id" value="{{ research.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                 </td>
                                 <td>
                                    <!--FIX HERE//-->
                                    <a href="{% url 'student:research-update' research.id %}" class="btn btn-primary btn-xs" role="button">
                                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>&nbsp; Edit
                                    </a>

                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>



        <!-- Right Song Info -->

        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h1>All course</h1>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                           <th>Courser Name</th>
                            <th>Section</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for course in lecturer.lecturerinsection_set.all %}
                            <tr>
                                <td>{{course.lecsec_sub_FK}}</td>
                                <td>{{course.lecsec_sec_FK}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>




    </div>

</div>

{% endblock %}

StudentRegistration_SunionS/student/templates/student/Sindex.html
{% extends 'student/base.html' %}
{% block students_active %}active{% endblock %}
{% block body %}
<div class="students-container container-fluid">


     <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'student:student-add'%}">Add New Student</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">


                    <h3>All Students</h3>

                    <form method='GET' action=''>
                        <input type='text' name='q' placeholder='Search student name'/>
                        <input type='submit' value='Search'/>
                    </form>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>name</th>
                            <th>Department</th>
                            <th>DOB</th>
                            <th>Tel</th>
                            <th>Degree</th>
                            <th>GPAX</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for student in all_students %}
                            <tr>
                                <td>{{ student.name }}</td>
                                <td>{{ student.stu_dep_FK.DepName }}</td>
                                 <td>{{ student.DOB }}</td>
                                 <td>{{ student.Tel }}</td>
                                <td>{{ student.Degree }}</td>
                                 <td>{{ student.GPAX }}</td>
                                <td>
                                   <a href="{% url 'student:student-update' student.id %}" class="btn btn btn-warning" role="button">Edit</a>
                                </td>
                                  <td>
                                <form action="{% url 'student:student-delete' student.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="student_id" value="{{ studemt.id }}" />
                                <button type="submit"class="btn btn-danger">
                                    <span class="glyphicon glyphicon-remove"></span>  Remove
                                </button>
                            </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

</div>
{% endblock %}

StudentRegistration_SunionS/student/templates/student/TestCart.html
{% extends 'student/base-student.html' %}

{% block body %}
    <h1 style="text-indent: 280px">Selected Courses</h1>


<div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>SubjectCode</th>
                            <th>SubjectName</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for student in all_student %}
                            {% if student.StudentID == user.username %}
                                {% for history in student.history_set.all %}
                                    {% if history.StudyYet == True %}
                                        {% if history.Grade == '-' %}
                                        <tr>
                                            <td>{{ history.his_subject_FK.SubjectID }}</td>
                                            <td>{{ history.his_subject_FK.SubjectName }}</td>
                                        </tr>
                                        {% endif %}
                                    {% endif%}
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                        </tbody>
                        </table>

                </div>
            </div>

    <br><br>
            <a style="font-size: 40px;" href="{% url 'student:add-subject' %}" class="btn btn-primary btn-lg " role="button"><i class="fa fa-plus" aria-hidden="true"></i> Add subject</a>


            {% for student in all_student %}
                {% if student.StudentID == user.username %}
                    {% for register in student.register_set.all %}
                        {% if register.Semester == student.CurrentSemester %}
                            <a style="font-size: 40px;" href="{% url 'student:register-update' register.id %}" class="btn btn-warning btn-lg " role="button"><i class="fa fa-check" aria-hidden="true"></i>submit</a>
                        {% endif %}
                    {% endfor%}
                {% endif %}
            {% endfor%}


    <br><br><a href="{% url 'student:student-manage' %}" class="btn btn-success btn-lg"><i class="fa fa-arrow-left fa-1x" aria-hidden="true"></i> Back to home</a>

</div>
{% endblock %}

StudentRegistration_SunionS/student/templates/student/add-subject.html
{% extends 'student/base-student.html' %}

{% block body %}
<h1 style="text-indent: 280px; "><strong>Add Subject page</strong></h1>

<div class="col-sm-4 col-md-8">
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>SubjectCode</th>
                        <th>SubjectName</th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in all_student %}
                        {% if student.StudentID == user.username %}
                            {% for history in student.history_set.all %}
                                {% if history.StudyYet == False %}
                                    <tr>
                                        <td>{{ history.his_subject_FK.SubjectID }}</td>
                                        <td>{{ history.his_subject_FK.SubjectName }}</td>
                                        <td>
                                            <a href="{% url 'student:subject-update' history.id %}" class="btn btn-primary btn-sm">
                                                <span class="glyphicon glyphicon-plus"></span> Plus
                                            </a>
                                        </td>
                                    </tr>
                            {% endif%}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'student:student-manage' %}" class="btn btn-success btn-lg"><i class="fa fa-arrow-left fa-1x" aria-hidden="true"></i> Back to home</a>
</div>



{% endblock %}

StudentRegistration_SunionS/student/templates/student/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home Page{% endblock%}</title>
    {% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'student/Bg.css' %} " />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>

<body>
<nav class = "navbar navbar-inverse">
    <p style="background-color:yellow">
    <div class="container-fluid">
        <!-- Logo -->
        <div class= "navbar-header">
            <button type="button" class="navbar-toggle" data-toggle ="collapse" data-target="">
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}"><font face="Satisfy" color="White"> Hello !! {{ user.username }} </font></a>
        </div>

        <!-- Items -->
        <div class = "collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'student:index' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span> &nbsp; Department
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'student:Sindex' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> &nbsp; Students
                    </a>
                </li>
            </ul>


            <ul class="nav navbar-nav navbar-right" >
                 <li class="">
                    <a href="{% url 'student:department-add'%}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> &nbsp; Add Department
                    </a>
                </li>
                 <li class="">
                    <a href="{% url 'logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span> &nbsp; Logout
                    </a>
                </li>
            </ul>



        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>

</html>

StudentRegistration_SunionS/student/templates/student/courseDetail.html
{% extends 'student/Lbase.html' %}
{% block title %}{{ subject }}{% endblock %}

{% block body %}
<div class="container-fluid subjects-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'student:Cdetail' subject.id %}">
                    </a>
                    <h1>{{ subject.SubjectID }}</h1>
                    <h2>{{ subject.SubjectName }}</h2>

                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Students</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Department</th>
                            <th>Degree</th>
                            <th>Grade</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for s in subject.history_set.all %}
                            {% if s.StudyYet == True %}
                            <tr>
                                <td>{{ s.his_student_FK.name }}</td>
                                <td>{{ s.his_student_FK.stu_dep_FK.DepName }}</td>
                                <td>{{ s.his_student_FK.Degree }}</td>
                                <td>{{ s.Grade }}</td>

                                  <td>
                                    <!--FIX HERE//-->
                                    <a href="{% url 'student:history-grade' s.id %}" class="btn btn-primary btn-xs" role="button">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Fill Grade
                                    </a>

                                </td>

                                <td>
                                <form action="{% url 'student:history-delete' s.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="student_id" value="{{ s.id }}" />
                                <button type="submit"class="btn btn-danger btn-xs">
                                    <span class="glyphicon glyphicon-remove"></span>  Remove
                                </button>
                                </form>
                                </td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

StudentRegistration_SunionS/student/templates/student/history.html
{% extends 'student/base-student.html' %}

{% block body %}
    <h1 style="text-indent: 280px">Student History page</h1>


<div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>SubjectCode</th>
                            <th>SubjectName</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for student in all_student %}
                            {% if student.StudentID == user.username %}
                                {% for history in student.history_set.all %}
                                    {% if history.StudyYet == True %}
                                    <tr>
                                        <td>{{ history.his_subject_FK.SubjectID }}</td>
                                        <td>{{ history.his_subject_FK.SubjectName }}</td>
                                        <td>
                                            <a href="{% url 'student:history-detail' history.id %}" class="btn btn-primary btn-xs" role="button">View Details</a>
                                        </td>
                                    </tr>
                                    {% endif%}
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                        </tbody>
                        </table>

                </div>
            </div>



    <a href="{% url 'student:student-manage' %}" class="btn btn-success btn-lg"><i class="fa fa-arrow-left fa-1x" aria-hidden="true"></i> Back to home</a>
</div>
{% endblock %}

StudentRegistration_SunionS/student/templates/student/lecturer_form.html
{% extends 'student/Lbase.html' %}
{% block title %}Add new lecturer{% endblock %}
{% block lecturer_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'student/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}