StudentRegistration_SunionS/login/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^analytic/', TemplateView.as_view(template_name='analytic.html'), name ='analy'),
    url(r'^student/', include('student.urls'), name = 'student'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StudentRegistration_SunionS/student/urls.py
from django.conf.urls import url
from . import views

app_name = 'student'

urlpatterns = [

    url(r'^$',views.IndexView.as_view(), name ='index'),

    url(r'^researchc$',views.ResearchCount, name ='research-count'),

    url(r'^totalclec/$', views.totalCostLec, name='totalc-lec'),

    url(r'^totalcdep/$', views.totalCostDep, name='totalc-dep'),

    url(r'^avgdep/$', views.AVGdepartment, name='avg-dep'),

    url(r'^students/$', views.StudentIndex, name='Sindex'),

    url(r'^studentform/$', views.StudentFormView, name='studentform'),

    url(r'^studentmanage/$', views.StudentManageView.as_view(), name='student-manage'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail' ),

    url(r'student/add/$', views.StudentCreate.as_view(), name='student-add'),

    url(r'student/(?P<pk>[0-9]+)/$', views.StudentUpdate.as_view(), name='student-update'),

    url(r'student/(?P<pk>[0-9]+)/delete/$', views.StudentDelete.as_view(), name='student-delete'),

    url(r'department/add/$',views.DepartmentCreate.as_view(), name='department-add'),

    url(r'department/(?P<pk>[0-9]+)/$', views.DepartmentUpdate.as_view(), name='department-update'),

    url(r'department/(?P<pk>[0-9]+)/delete/$', views.DepartmentDelete.as_view(), name='department-delete'),

    url(r'^lindex/$', views.LIndexView.as_view(), name='Lindex'),

    url(r'^lindex/(?P<pk>[0-9]+)/$',views.LDetailView.as_view(), name='Ldetail'),

    url(r'lecturer/lindex/add/$',views.LecturerCreate.as_view(), name='lecturer-add'),

    url(r'research/lindex/add/$', views.ResearchCreate.as_view(), name='research-add'),

    url(r'lecturer/lindex/(?P<pk>[0-9]+)/$', views.LecturerUpdate.as_view(), name='lecturer-update'),

    url(r'research/lindex/(?P<pk>[0-9]+)/$', views.ResearchUpdate.as_view(), name='research-update'),

    url(r'research/lindex/(?P<pk>[0-9]+)/delete/$', views.ResearchDelete.as_view(), name='research-delete'),

    url(r'lecturer/lindex/(?P<pk>[0-9]+)/delete/$', views.LecturerDelete.as_view(), name='lecturer-delete'),

    url(r'course/lindex/add/$', views.CourseCreate.as_view(), name='course-add'),

    url(r'course/lindex/assign/$', views.AssignLecturer.as_view(), name='course-assign'),

    url(r'^course/$', views.CIndexView.as_view(), name='Cindex'),

    url(r'^course/lindex/(?P<pk>[0-9]+)/$', views.CDetailView.as_view(), name='Cdetail'),

    url(r'history/lindex/upgrade/(?P<pk>[0-9]+)/$', views.HistoryUpdate.as_view(), name='history-grade'),

    url(r'history/lindex/delete/(?P<pk>[0-9]+)/$', views.HistoryDelete.as_view(), name='history-delete'),

    url(r'course/lindex/upgrade/(?P<pk>[0-9]+)/$', views.CourseUpdate.as_view(), name='course-update'),

    url(r'course/lindex/delete/(?P<pk>[0-9]+)/$', views.CourseDelete.as_view(), name='course-delete'),

    url(r'^studentmanage/history/$', views.StudentHistory.as_view(), name='student-history'),

    url(r'^studentmanage/history/(?P<pk>[0-9]+)/$', views.HistoryDetail.as_view(), name='history-detail'),

    url(r'^studentmanage/test/add/$', views.AddSubject.as_view(), name='add-subject'),

    url(r'^studentmanage/test/add/(?P<pk>[0-9]+)/$', views.SubjectUpdate.as_view(), name='subject-update'),

    url(r'^students/profile/$', views.SDetailView.as_view(), name='Sdetail'),

    url(r'^studentmanage/test/$', views.Test.as_view(), name='Test'),

    url(r'^studentmanage/test/(?P<pk>[0-9]+)/$', views.RegisterUpdate.as_view(), name='register-update'),



]

StudentRegistration_SunionS/login/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password',]

StudentRegistration_SunionS/login/views.py
from django.contrib.auth import login, authenticate
from django.views.generic import View
from login.forms import UserForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader

class UserFormView(View):
    form_class = UserForm
    template_name = 'signup.html'
    # display blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    # process form data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return User objects if credentials are correct
            user = authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request,user)
                    return redirect('home')
        return render(request,self.template_name,{'form':form})

StudentRegistration_SunionS/templates/analytic.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css" />


<br>

<body>
<div class="col-md-9 text-center">

                        <h1> Analysis Report </h1>
     <br><br><br>
      <a href="{% url 'student:avg-dep' %}" class="btn btn-primary btn-lg"><h1> <i class="fa fa-users" aria-hidden="true"></i> Analysis Report - AVG dep </h1></a>
      <br><br><br>
      <a href="{% url 'student:totalc-dep' %}" class="btn btn-success btn-lg"><h1><i class="fa fa-money" aria-hidden="true"></i> Analysis Report - total revenue dep </h1></a>
      <br><br><br>
      <a href="{% url 'student:totalc-lec' %}" class="btn btn-warning btn-lg"><h1><i class="fa fa-user" aria-hidden="true"></i> Analysis Report - total count lecturer </h1></a>
      <br><br><br>
       <a href="{% url 'student:research-count' %}" class="btn btn-danger btn-lg"><h1> <i class="fa fa-book" aria-hidden="true"></i> Analysis Report - research categories </h1></a>
    <br><br><br>
    <a href="{% url 'home' %}" class="btn btn-success">Back to home</a>
</div>
</body>

StudentRegistration_SunionS/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Login{% endblock %}</title>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" type="text/css" />


</head>

<body>


<nav class = "navbar navbar-inverse">
    <p style="background-color:yellow">
    <div class="container-fluid">
        <!-- Logo -->
        <div class= "navbar-header">
            <button type="button" class="navbar-toggle" data-toggle ="collapse" data-target="">
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
                <span class = "icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}"><font color="White">  Student Registration System </font></a>
        </div>

        <!-- Items -->
        <div class = "collapse navbar-collapse">


       <ul class="nav navbar-nav navbar-right" >

                 {% if user.is_authenticated %}
                   <a class="navbar-brand" ><font face="Satisfy" color="White">  Hello!! </font></a>
                   <a class="navbar-brand"><font face="Satisfy" color="White">  {{ user.username }} </font></a>

                  {% endif %}
                 <li class="">
                    <a href="{% url 'logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span> &nbsp; Logout
                    </a>
                </li>
       </ul>



        </div>

    </div>

</nav>

{% if user.is_authenticated == False %}
  <ul class="nav nav-tabs">
  <li><a href="{% url 'login' %}">Login</a></li>
  <li><a href="{% url 'register' %}">SignUp</a></li>
</ul>

{% endif %}



{% block body %}
{% endblock %}

  <header>
    {% if user.is_authenticated and user.is_superuser %} <!--admin-->
    <h1><font color="Grey">  What you want to do ? </font></h1>
       <br>
      <a href="{% url 'student:index' %}" class="btn btn-warning btn-lg"><h1> <i class="fa fa-pencil fa-4x" aria-hidden="true"></i> Manage Department & Student</h1></a>
      <a href="{% url 'student:Lindex' %}" class="btn btn-danger btn-lg"><h1> <i class="fa fa-users fa-4x" aria-hidden="true"></i>Manage Lecturer</h1></a>
      <br><br><br>
           <a href="{% url 'analy' %}" class="btn btn-info btn-lg"><h1> <span class="glyphicon glyphicon-info-sign"></span> Analysis Report </h1></a>

      {% elif user.is_authenticated and 'l' in user.username %} <!--Teacher-->
        <h1><font color="Grey">  What you want to do ? </font></h1>
       <br>
        <a href="{% url 'student:Lindex' %}" class="btn btn-danger btn-lg"><h1><i class="fa fa-user fa-4x" aria-hidden="true"></i> View Profile (Lecturer only)</h1></a>
        <br><br><br>
            <a href="{% url 'analy' %}" class="btn btn-info btn-lg"><h1> <span class="glyphicon glyphicon-info-sign"></span> Analysis Report </h1></a>



    {% elif user.is_authenticated %} <!--student-->
     <h1><font color="Grey">  What you want to do ? </font></h1>
      <br>
      <a href="{% url 'student:Sdetail' %}" class="btn btn-primary btn-lg"><h1> <i class="fa fa-user fa-4x" aria-hidden="true"></i> Go to student form</h1></a>
      <a href="{% url 'student:student-manage' %}" class="btn btn-warning btn-lg"><h1> <i class="fa fa-pencil-square-o fa-4x" aria-hidden="true"></i> Add subject this semester</h1></a>
      <br><br><br>
      <a href="{% url 'analy' %}" class="btn btn-info btn-lg"><h1> <span class="glyphicon glyphicon-info-sign"></span> Analysis Report </h1></a>

    {% else %}

    {% endif %}


  </header>
  <hr>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <hr>
</body>
</html>

StudentRegistration_SunionS/templates/home.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

StudentRegistration_SunionS/templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

StudentRegistration_SunionS/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
 {% if user.is_authenticated %}

{% else %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log in</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'student/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Log in</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>


    </div>
</div>


{% endif %}
{% endblock %}

StudentRegistration_SunionS/templates/signup.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block body %}

{% if user.is_authenticated %}

{% else %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                      <input type="hidden" name="csrfmiddlewaretoken" value="3l99jziFt2r0O1DGlQpsH85AAsbGjptdqyC28BAudnZRqKr4MKeGvrkiuN5fdqdW">

  <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
          <span class="text-danger small"></span>
      </div>
      <label class="control-label col-sm-2"><label for="id_username">Username:</label></label>
      <div class="col-sm-10"><input type="text" name="username" maxlength="150" required="" id="id_username"></div>
  </div>


  <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
          <span class="text-danger small"></span>
      </div>
      <label class="control-label col-sm-2"><label for="id_email">Email address:</label></label>
      <div class="col-sm-10"><input type="email" name="email" maxlength="254" id="id_email"></div>
  </div>


  <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
          <span class="text-danger small"></span>
      </div>
      <label class="control-label col-sm-2"><label for="id_password">Password:</label></label>
      <div class="col-sm-10"><input type="password" name="password" maxlength="128" required="" id="id_password"></div>
  </div>




                        {% csrf_token %}
                        <!-- {% include 'student/form-template.html' %} -->
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>


    </div>
</div>
{% endif %}
{% endblock %}